# Generated by Django 5.1.4 on 2026-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('abstract', models.TextField(blank=True, default='')),
                ('body', models.TextField(help_text='Markdown. Headings, lists and fenced code blocks render in phosphor.')),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
