// Compiles src/wasm/core.wat → src/wasm/core.wasm using wabt (wat2wasm).
// Usage: node scripts/build-wasm.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const watPath = resolve(root, "src/wasm/core.wat");
const outPath = resolve(root, "src/wasm/core.wasm");

const initWabt = (await import("wabt")).default;
const wabt = await initWabt();

const wat = readFileSync(watPath, "utf8");
const module = wabt.parseWat("core.wat", wat);
module.validate();
const { buffer } = module.toBinary({ log: false, write_debug_names: false });

mkdirSync(dirname(outPath), { recursive: true });
const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
writeFileSync(outPath, bytes);

// Also embed the binary as base64 in a TS module so the build never
// depends on the .wasm artifact surviving file transfers / .gitignore.
const b64Path = resolve(root, "src/wasm/core.b64.ts");
const b64 = Buffer.from(bytes).toString("base64");
writeFileSync(
  b64Path,
  [
    "// AUTO-GENERATED by scripts/build-wasm.mjs — do not edit.",
    `// base64 of core.wasm (${bytes.length} bytes). Regenerate: node scripts/build-wasm.mjs`,
    `export const CORE_WASM_BASE64 = "${b64}";`,
    "",
  ].join("\n")
);

console.log(`core.wasm written → ${outPath} (${bytes.length} bytes)`);
console.log(`core.b64.ts written → ${b64Path} (${b64.length} chars)`);

// Smoke test
const { instance } = await WebAssembly.instantiate(bytes);
const e = instance.exports;
const ok = e.fib(10) === 55 && (e.fnv1a(0, 0) >>> 0) === 2166136261;
console.log(
  `smoke: fib(10)=${e.fib(10)} fnv1a("")=0x${(e.fnv1a(0, 0) >>> 0).toString(16)} xorshift(1)=${e.xorshift32(1)} version=${e.core_version()} ${ok ? "PASS" : "FAIL"}`
);
if (!ok) process.exit(1);
